### ISSUE TITLE
Link redirection for Various Roles on Community Roles Page doesn't point to respective Role descriptions

### ISSUE THREAD

**Issue by DhruvSondhi** [tardis-sn/tardis-sn.github.io#30]
**Describe the bug**
The `More Info` link on all the picture grid on the website should point to the particular role's description on the Community Roles Page for the website. They need to be redirected correctly or else removed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/66117751/145463943-16d01fa1-1960-46d0-ab9d-05a404f89b52.png)
More Info here doesn't lead to the particular role's description

**Comment by jaladh-singhal** [comment]
"More info" is for informaion about the core team member not the role. For role, click on the text itself - as mentioned right above picture grid.

> Current TARDIS core team members are as follows (you can click on the role to learn more about it):

**Comment by jaladh-singhal** [comment]
Captured the real issue in #31 - hence closing it.
